### ISSUE TITLE
라이센스 관련

### ISSUE THREAD

**Issue by jeff-lim** [codeforseoul/gettingstarted#11]
gettingstarted 레포에는 아직 readme.md는거 같은데
라이센스 텍스트 파일은 없어도 되는게 맞지 않나요? 내용도 소프트웨어에 대한 라이센스 조항이더라고요.

**Comment by thechunsik** [comment]
퍼블릭도메인을 사용한 소프트웨어 파일을 그대로 가져왔던 것 같은데 그러네요 ㅋ CC0 조만간 변경해둘게요~!

**Comment by thechunsik** [comment]
수정하였습니다
