### ISSUE TITLE
코드를 몰라요 - 근데 하고 싶어요!

### ISSUE THREAD

**Issue by mozodev** [codeforseoul/gettingstarted#9]
오늘 마루에 왔는데 부산코더스들과 이야기하다가 뭔가 잘 모르는데
웹사이트를 만들고 싶은데 어디를 가야하는지 모르겠다고 하셔서.... 음 생각이 났어요...

코드를 모르는 사람이 뭔가 배워보고 싶어하는 경우도 
문서에 좀 포함을 시켰으면 하는데 이런 경우
http://opentutorials.org/course/1

여기를 추천해주는게 좋을까요?
아님 마크업 스타일링이나
언어별로 국문, 영문별로 커뮤니티나 서비스 링크를 좀 정리해서 포함시키면 어떨가하는데
의견을 좀 모아보고 문서에 추가했으면 좋겠습니다. 
이거 보시고 생각나는 분들 의견 주시거나 리드미에 추가해주세요.

**Comment by mozodev** [comment]
음 불특정 다수를 대상으로 코드를 가르치는게 아니고 하고 싶은 사람들, 예를 들면 드물수도 있지만 디자이너가 마크업과 스타일링을 배우고 싶다. 이런 경우는 아주 좋은 경우인게 프로젝트에 좀 더 참여할 수 있는거죠. 시각적 결과물만 만들어내는게 아니라.... 또는 자바 밖에 모르는 분들이 파이썬이나 노드 등 다른 언어에 대한 경험을 해볼 수 있도록? 다시 말하자면 프로젝트를 잘 하기 위해서 내부 역량을 축적하고 정보와 기술을 공유하기 위한 그런거죠.... 

저도 뭔가 기술 자체를 배우기위해 찾아오는 사람들을 대상으로 하는건 아니라고 생각해요...

음 이걸 소개 문서에 넣는건 시기 상조일 듯 하네요... 
팀 블로그를 하나 만들어서 기술 문서를 쌓아가면 어떨까 싶은데요. 
뭔가 배우고 싶은 사람들이 늘어나면 핵나잇이든 필요한 사람들이 모여서 스터디를 진행할 수도 있겠고요... ㅎ

일단 닫습니다.

**Comment by statkclee** [comment]
코드포서울이라서... 서울에서 코드 가르치나라고 생각하시는 분이 많나봐요... 이름을 바꾸던지... 요즘... 코딩이 하두 인기검색어라... 코드는 대부분의 사람들이 배우는 것 ... 학습하는것... 그래서... 코드포서울은... 그런 의미에서는 좋을 수도.. ㅎㅎ

**Comment by jeff-lim** [comment]
코드포서울 브랜드에 있는 코드가 소스코드만을 지칭하는 건 아닌거 같아요.
(코드포아메리카는 좀더 소스코드의 코드에 가까운 것 같지만..)

우리가 생각하는 코드, 코드포, 코드포서울에 대해 설명/논의도 해보면 좋을 거 같아요.

"나는 누구? 여긴 어디?"

-영제
2015. 1. 7. 오전 11:49에 "Kwangchun Lee" <notifications@github.com>님이 작성:
